### ISSUE TITLE
AttributeError: 'function' object has not attribute 'get'

### ISSUE THREAD

**Issue by mikuyourworld** [pcrbot/vtb-bili#3]
添加模块启动hoshino以后出现这个错误
![Screenshot 2021-10-28 161319](https://user-images.githubusercontent.com/30253025/139218226-85c8e450-0b15-402f-a201-452d73ef8607.jpg)

**Comment by runswell** [comment]
59行bilibili_vtbs = filter(lambda x: len(x["accounts"]) != 0 and [lambda a: a["platform"]=='bilibili',x["accounts"]][0].get("platform") == 'bilibili', data)
改为bilibili_vtbs = filter(lambda x: len(x["accounts"]) != 0 and [lambda a: a["platform"]=='bilibili',x["accounts"][0].get("platform") == 'bilibili'], data)即可
很显然有一个中括号出现在了错误的位置
