### ISSUE TITLE
关于vtb名单缺漏问题

### ISSUE THREAD

**Issue by HateTomato** [pcrbot/vtb-bili#4]
以我个人为例
我关注的[高槻律official](https://space.bilibili.com/6055289/)以及[Overidea_China](https://space.bilibili.com/18149131/)在[vtbs.moe](vtbs.moe)上均能查询到，但是用插件查询就无法识别，能不能查一查是什么原因

**Comment by HateTomato** [comment]
好，谢谢

**Comment by kosakarin** [comment]
> 好，谢谢
在更新vtb列表那个函数里，获取data后面加入以下暴力处理代码，强行将bilbili account排到[0]位置上就可以了，我这边的测试结果是一个之前20位的暴力处理完成后可以查出来28位，ho的那些都能查出来了
        for i in data:
            for ii in range(0,10):
                try:
                    if i["accounts"][ii].get("platform") == 'bilibili':
                        i["accounts"][0] = i["accounts"][ii]
                        break
                except:
                    break

**Comment by kosakarin** [comment]
这里是添加这段代码前后的效果比对：
关注的vtb有20位，TA们是：
昙露拾珠Channel，羽澄照乌愈，玩具喵，小凌漆漆，新月冰冰，沐莺，向晚大魔王，Project_NyaRi，コグレ，菜菜子Nanako，御剣莉亚-官方，多多poi，疾風醬，冬雪もも_shy，步玎Pudding，SoulliesOfficial，东爱璃Lovely，嘉然今天吃什么，月兔华，阿萨Aza
_________

关注的vtb有28位，TA们是：
高槻律，冬雪もも_shy，昙露拾珠Channel，SoulliesOfficial，月兔华，小狼，かぐらなな，Project_NyaRi，羽澄照乌愈，キズナアイ，新月冰冰，Overidea(OR)公式，御剣莉亚-官方，菜菜子Nanako，小凌漆漆，阿萨Aza，向晚大魔王，嘉然今天吃什么，疾風醬，玩具喵，湊あくあ，多多poi，神楽めあ，步玎Pudding，东爱璃Lovely，沐莺，鹿乃，コグレ

**Comment by kosakarin** [comment]
因为这是个暴力处理，所以需要大概两到三秒的时间来完成，顺便我推荐把启动时更新修改为定时更新或者关键字更新

**Comment by HateTomato** [comment]
感谢，辛苦了
